services:
  vaultwarden:
    image: vaultwarden/server:1.36.0
    restart: always
    environment:
      DOMAIN: ${DOMAIN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    volumes:
      - vaultwarden:/data
    expose:
      - 80

volumes:
  vaultwarden:
